# Generated by Django 3.2 on 2022-08-12 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_parent'),
        ('account', '0003_remove_user_product_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_device_count', models.PositiveIntegerField(default=0)),
                ('device_count', models.PositiveBigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProductPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_device_count', models.PositiveIntegerField(default=0)),
                ('device_count', models.PositiveBigIntegerField(default=0)),
                ('product', models.ForeignKey(limit_choices_to={'product_type': 'plugin'}, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('product', 'user')},
            },
        ),
    ]
