# Generated by Django 3.2 on 2022-08-13 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userapppermission_userproductpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
