# Generated by Django 3.2 on 2022-08-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_parent'),
        ('account', '0005_alter_userproductpermission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
