# Generated by Django 3.2 on 2022-08-23 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_parent'),
        ('account', '0006_user_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapppermission',
            name='product',
            field=models.ForeignKey(default=1, limit_choices_to={'product_type': 'plugin'}, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userapppermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
