# Generated by Django 3.2 on 2022-08-23 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_parent'),
        ('account', '0007_auto_20220823_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapppermission',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type': 'normal'}, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
