# Generated by Django 3.2 on 2022-09-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20220824_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='files_paths',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
