# Generated by Django 3.2 on 2022-09-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_files_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='files_paths',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
    ]
