# Generated by Django 3.2 on 2022-09-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_files_paths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='files_paths',
        ),
    ]
