# Generated by Django 3.2 on 2022-07-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_devicetoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidorder',
            name='device_limit',
            field=models.IntegerField(default=0),
        ),
    ]
