# Generated by Django 3.2 on 2022-07-30 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_paidorder_device_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidorder',
            name='device_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.devicetoken'),
        ),
    ]
