# Generated by Django 3.2 on 2022-08-05 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_paidorder_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.product'),
        ),
    ]
