# Generated by Django 3.2 on 2022-08-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_paidorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('premium', 'پرمیوم'), ('normal', 'معمولی'), ('all-in-one', 'آل این وان')], default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paidorder',
            name='wp_order_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
