# Generated by Django 3.2 on 2022-08-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20220805_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidorder',
            name='device_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.devicetoken'),
        ),
    ]
