# Generated by Django 3.2 on 2022-08-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_paidorder_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wp_product_id',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
