# Generated by Django 3.2 on 2022-08-07 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('order', '0008_product_wp_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidorder',
            name='manual_permission',
        ),
        migrations.RemoveField(
            model_name='paidorder',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='paidorder',
            name='rose_permission',
        ),
        migrations.AlterField(
            model_name='paidorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.DeleteModel(
            name='ManualPermission',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
