# Generated by Django 3.2 on 2022-08-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_parent'),
        ('order', '0009_auto_20220807_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidorder',
            name='product',
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='plugins',
            field=models.ManyToManyField(limit_choices_to={'product_type': 'plugin'}, related_name='linked_plugins', to='products.Product'),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='products',
            field=models.ManyToManyField(limit_choices_to={'product_type': 'normal'}, related_name='linked_products', to='products.Product'),
        ),
        migrations.AddField(
            model_name='paidorder',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
