# Generated by Django 3.2 on 2022-08-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220812_1845'),
        ('order', '0011_auto_20220812_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='plugins',
            field=models.ManyToManyField(blank=True, limit_choices_to={'product_type': 'plugin'}, related_name='linked_plugins', to='products.Product'),
        ),
    ]
