# Generated by Django 3.2 on 2022-08-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_devicetoken_plugins'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='expired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
