# Generated by Django 3.2 on 2022-08-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_devicetoken_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='device_uuid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
