# Generated by Django 3.2 on 2022-09-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_devicetoken_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='file_paths',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
    ]
