# Generated by Django 3.2 on 2022-08-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PieceOfCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='عنوان')),
                ('code', models.TextField()),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='عنوان فایل')),
                ('associated_file', models.FileField(upload_to='products/', verbose_name='فایل')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='توضیحات')),
                ('device_count_permission', models.PositiveIntegerField(blank=True, null=True, verbose_name='دسترسی تعداد دیوایس')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='نام محصول')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='نامک')),
                ('permalink', models.URLField(blank=True, null=True)),
                ('wp_product_id', models.PositiveIntegerField(unique=True, verbose_name='آی دی محصول در وردپرس')),
                ('status', models.CharField(max_length=32, verbose_name='وضعیت')),
                ('codes', models.ManyToManyField(to='products.PieceOfCode', verbose_name='کد(ها)')),
                ('files', models.ManyToManyField(to='products.ProductFile', verbose_name='فایل(ها)')),
                ('permissions', models.ManyToManyField(to='products.ProductPermission', verbose_name='دسترسی ها')),
            ],
        ),
    ]
