# Generated by Django 3.2 on 2022-08-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pieceofcode',
            options={'verbose_name': 'کد', 'verbose_name_plural': 'کد ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productfile',
            options={'verbose_name': 'فایل محصول', 'verbose_name_plural': 'فایل ها'},
        ),
        migrations.AlterModelOptions(
            name='productpermission',
            options={'verbose_name': 'دسترسی', 'verbose_name_plural': 'دسترسی ها'},
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('normal', 'معمولی'), ('plugin', 'پلاگین'), ('other', 'دیگر')], default='normal', max_length=20, verbose_name='نوع'),
        ),
    ]
