# Generated by Django 3.2 on 2022-08-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parent',
        ),
        migrations.AddField(
            model_name='product',
            name='plugins',
            field=models.ManyToManyField(blank=True, limit_choices_to={'product_type': 'plugin'}, related_name='_products_product_plugins_+', to='products.Product', verbose_name='پلاگین(ها)'),
        ),
    ]
