# Generated by Django 3.2 on 2022-08-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220824_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBCompatibaleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='productfile',
            name='associated_file',
            field=models.FileField(upload_to='products.DBCompatibaleFile/bytes/filename/mimetype', verbose_name='فایل'),
        ),
    ]
