# Generated by Django 3.2 on 2022-08-29 20:33

from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220830_0022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DBCompatibaleFile',
        ),
        migrations.AlterField(
            model_name='productfile',
            name='associated_file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='products/', verbose_name='فایل'),
        ),
    ]
